"""
Django settings for EbbinghausAnywhere project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import environ

env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


# 读取 .env 文件（如果存在）
# 注意：优先从环境变量读取，Docker 会通过 env_file 注入环境变量
environ.Env.read_env(BASE_DIR / '.env')

# SECRET_KEY 必须通过环境变量设置（Docker 部署时由 docker-compose.yml 注入）
SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = ['*']

# CORS 配置
CORS_ALLOW_ALL_ORIGINS = True  # 允许所有来源（开发环境）
CORS_ALLOW_CREDENTIALS = True  # 允许携带认证信息
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "EAW.apps.EawConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "EbbinghausAnywhere.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates',],  # 确保包含全局模板路径
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.csrf",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "EbbinghausAnywhere.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# 安全设置 - 允许在 iframe 中加载（用于五子棋游戏）
X_FRAME_OPTIONS = 'SAMEORIGIN'  # 允许同源页面在 iframe 中加载
SECURE_SSL_REDIRECT = False  # 开发环境不强制 HTTPS
SECURE_HSTS_SECONDS = 0  # 开发环境禁用 HSTS
SESSION_COOKIE_SECURE = False  # 开发环境允许 HTTP
CSRF_COOKIE_SECURE = False  # 开发环境允许 HTTP

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 静态文件的存放路径
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # 收集的静态文件最终存放路径

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # 默认认证后端
)

# 登录和退出后的跳转路径
LOGIN_URL = '/accounts/login/'  # 用户未登录时，跳转的登录页面
LOGOUT_URL = 'home'  # 退出登录后跳转的页面
LOGIN_REDIRECT_URL = 'home'  # 登录成功后跳转的页面

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',  # 指定使用 UTF-8 编码
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],  # 只使用文件日志
            'level': 'DEBUG',
            'propagate': False,  # 不传播到控制台
        },
        'django.db.backends': {
            'handlers': ['file'],  # SQL 查询只记录到文件
            'level': 'DEBUG',
            'propagate': False,  # 不传播到父 logger
        },
    },
}

# DeepSeek API Configuration
DEEPSEEK_API_KEY = env('DEEPSEEK_API_KEY', default=None)
DEEPSEEK_BASE_URL = env('DEEPSEEK_BASE_URL', default='https://api.deepseek.com')

try:
    from .local_settings import *
except ImportError:
    pass

# 开发方便：允许所有源进行跨域请求（生产环境请改为精确白名单）
CORS_ALLOW_ALL_ORIGINS = True
