# Generated by Django 5.1.3 on 2024-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EAW", "0007_item_uk_phonetic_item_us_phonetic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="content",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
