# Generated by Django 5.1.3 on 2024-12-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EAW", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="catagory",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the item type, word or phrase",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="EAW.category",
            ),
        ),
    ]
