# Generated by Django 4.1 on 2024-12-07 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("EAW", "0005_category_is_default"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
    ]
