# Generated by Django 4.1 on 2024-12-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EAW", "0006_alter_item_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="uk_phonetic",
            field=models.CharField(
                blank=True,
                help_text="British Phonetic (optional)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="us_phonetic",
            field=models.CharField(
                blank=True,
                help_text="American Phonetic (optional)",
                max_length=200,
                null=True,
            ),
        ),
    ]
