# Generated by Django 5.2.10 on 2026-02-01 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAW', '0008_alter_item_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSeekConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='deepseek-chat', help_text='DeepSeek 模型名称', max_length=50)),
                ('temperature', models.FloatField(default=1.0, help_text='生成温度 (0.0-2.0)，数据抽取建议1.0，翻译建议1.3，创意写作建议1.5')),
                ('system_prompt', models.TextField(default='你是英语词典助手。输入：英文单词。输出：JSON格式包含uk_phonetic(英音标)、us_phonetic(美音标)、meaning(中文释义)、example_sentences(2-3个例句数组，每个包含english和chinese字段)。目标用户：小学5年级。严格按照JSON格式输出，不要添加任何其他文字或markdown代码块标记。', help_text='系统提示词，定义 DeepSeek 的行为和输出格式')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用 DeepSeek API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DeepSeek Configuration',
                'verbose_name_plural': 'DeepSeek Configurations',
            },
        ),
    ]
