# Generated by Django 5.2.10 on 2026-02-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAW', '0009_deepseekconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_interval',
            field=models.IntegerField(default=0, help_text='Current review interval in days (0,1,2,4,7,15,30,90,180,365)'),
        ),
        migrations.AddField(
            model_name='item',
            name='extra_review_since',
            field=models.DateField(blank=True, help_text='Extra review start date', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='needs_extra_review',
            field=models.BooleanField(default=False, help_text='Needs extra review (marked after clicking NO)'),
        ),
        migrations.AddField(
            model_name='item',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Next scheduled review date', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unfamiliar_history',
            field=models.JSONField(blank=True, default=list, help_text='History of unfamiliar markings'),
        ),
    ]
