# Generated by Django 5.2.10 on 2026-02-06 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAW', '0011_set_admin_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepseekconfig',
            name='temperature',
            field=models.FloatField(default=1.0, help_text='生成温度 (0.0-2.0)，数据抽取、英语词典建议1.0，翻译建议1.3，创意写作建议1.5'),
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.IntegerField(default=0, help_text='当前可用积分')),
                ('total_earned', models.IntegerField(default=0, help_text='累计获得积分（历史总和）')),
                ('total_spent', models.IntegerField(default=0, help_text='累计消费积分')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Points',
                'verbose_name_plural': 'User Points',
            },
        ),
        migrations.CreateModel(
            name='UserPointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_per_point', models.FloatField(default=1.0, help_text='1积分可以兑换的游戏时长（分钟）', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('redemption_step', models.IntegerField(default=10, help_text='兑换时加减按钮的步长（分钟）')),
                ('min_redemption_minutes', models.IntegerField(default=1, help_text='单次最少兑换多少分钟')),
                ('max_redemption_minutes', models.IntegerField(default=300, help_text='单次最多兑换多少分钟')),
                ('daily_checkin_enabled', models.BooleanField(default=True)),
                ('daily_checkin_points', models.IntegerField(default=1, help_text='每天签到奖励积分')),
                ('streak_reward_enabled', models.BooleanField(default=True)),
                ('streak_reward_points', models.IntegerField(default=5, help_text='连续学习N天后的额外奖励积分')),
                ('streak_reward_days', models.IntegerField(default=7, help_text='连续学习多少天触发奖励')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Points Config',
                'verbose_name_plural': 'User Points Configs',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='当前连续学习天数')),
                ('longest_streak', models.IntegerField(default=0, help_text='最长连续学习天数')),
                ('last_study_date', models.DateField(blank=True, help_text='最后一次学习日期', null=True)),
                ('current_checkin_streak', models.IntegerField(default=0, help_text='当前连续签到天数')),
                ('longest_checkin_streak', models.IntegerField(default=0, help_text='最长连续签到天数')),
                ('last_checkin_date', models.DateField(blank=True, help_text='最后一次签到日期', null=True)),
                ('last_streak_reward_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak',
                'verbose_name_plural': 'User Streaks',
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('EARN', '获得积分'), ('SPEND', '消费积分'), ('ADJUST', '管理员调整')], help_text='变动类型', max_length=10)),
                ('points', models.IntegerField(help_text='变动积分（正数为获得，负数为消费）')),
                ('reason', models.CharField(help_text='变动原因', max_length=200)),
                ('reference_id', models.CharField(blank=True, help_text='关联对象ID（如Item ID或Redemption ID）', max_length=100, null=True)),
                ('balance_after', models.IntegerField(help_text='变动后余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point History',
                'verbose_name_plural': 'Point Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='EAW_pointhi_user_id_fbb2e2_idx'), models.Index(fields=['change_type', '-created_at'], name='EAW_pointhi_change__1d0b49_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.IntegerField(help_text='消费积分')),
                ('game_minutes', models.IntegerField(help_text='兑换的游戏时长（分钟）')),
                ('exchange_rate', models.FloatField(help_text='兑换时的汇率（分钟/积分）')),
                ('status', models.CharField(choices=[('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='COMPLETED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Redemption',
                'verbose_name_plural': 'Point Redemptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='EAW_pointre_user_id_82a658_idx'), models.Index(fields=['status', '-created_at'], name='EAW_pointre_status_af0b9f_idx')],
            },
        ),
    ]
