# Generated by Django 5.2.10 on 2026-02-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EAW", "0012_alter_deepseekconfig_temperature_userpoints_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpointsconfig",
            name="daily_checkin_points",
            field=models.IntegerField(default=5, help_text="每天签到奖励积分"),
        ),
    ]
