# Generated by Django 5.2.10 on 2026-03-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EAW", "0013_change_daily_checkin_points_to_5"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="词汇表名称，如'2025上海市中考词汇'", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="词汇表描述")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="词汇等级，如'中考'、'高考'、'四级'",
                        max_length=50,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, help_text="源文件名", max_length=500),
                ),
                ("word_count", models.IntegerField(default=0, help_text="单词数量")),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="系统提示词，用于批量获取例句。留空则使用用户默认DeepSeek配置",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vocabulary Book",
                "verbose_name_plural": "Vocabulary Books",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.IntegerField(help_text="序号")),
                ("word", models.CharField(help_text="英文单词", max_length=200)),
                (
                    "meaning",
                    models.TextField(
                        help_text="中文释义（包含词性，如'n. 旗帜，旗帜'）。获取例句后会追加到末尾"
                    ),
                ),
                (
                    "us_phonetic",
                    models.CharField(blank=True, help_text="美式音标", max_length=200),
                ),
                (
                    "uk_phonetic",
                    models.CharField(blank=True, help_text="英式音标", max_length=200),
                ),
                (
                    "has_examples",
                    models.BooleanField(default=False, help_text="是否已获取例句"),
                ),
                (
                    "vocabulary_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="EAW.vocabularybook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocabulary Entry",
                "verbose_name_plural": "Vocabulary Entries",
                "ordering": ["vocabulary_book", "sequence_number"],
                "indexes": [
                    models.Index(
                        fields=["vocabulary_book", "sequence_number"],
                        name="EAW_vocabul_vocabul_d34665_idx",
                    )
                ],
                "unique_together": {("vocabulary_book", "sequence_number")},
            },
        ),
    ]
