# Generated by Django 5.2.10 on 2026-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EAW", "0014_vocabularybook_vocabularyentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularyentry",
            name="is_marked",
            field=models.BooleanField(
                default=False, help_text="是否带星号（重点词汇）"
            ),
        ),
    ]
