# Generated by Django 5.2.10 on 2026-08-17 17:22
# 峰谷定价适配：ModelPricing/DeepSeekUsageLog 两表 + 新价格体系种子
# 依据《DeepSeek_API_峰谷定价适配指南》（2026-08-17 生效）

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# 新价格表（元/百万 tokens，指南§2；高峰 = 空闲 × 2）
PRICING_SEED = [
    {
        "model_name": "deepseek-v4-flash",
        "offpeak_cache_hit_price": Decimal("0.0500"),
        "offpeak_cache_miss_price": Decimal("1.5000"),
        "offpeak_output_price": Decimal("4.5000"),
        "peak_cache_hit_price": Decimal("0.1000"),
        "peak_cache_miss_price": Decimal("3.0000"),
        "peak_output_price": Decimal("9.0000"),
        "price_source": "official-pricing:2026-08-17",
    },
    {
        "model_name": "deepseek-v4-pro",
        "offpeak_cache_hit_price": Decimal("0.1500"),
        "offpeak_cache_miss_price": Decimal("4.5000"),
        "offpeak_output_price": Decimal("13.5000"),
        "peak_cache_hit_price": Decimal("0.3000"),
        "peak_cache_miss_price": Decimal("9.0000"),
        "peak_output_price": Decimal("27.0000"),
        "price_source": "official-pricing:2026-08-17",
    },
]


def seed_pricing(apps, schema_editor):
    """写入新价格体系种子。

    update_or_create 幂等：部分执行后重跑不会重复建行、不会报错；
    若管理员已改过价格，正向重跑会覆盖为新价——这是"直接切换新价"
    的预期语义（指南§5 明确不保留旧价过渡逻辑）。
    """
    ModelPricing = apps.get_model("EAW", "ModelPricing")
    for row in PRICING_SEED:
        ModelPricing.objects.update_or_create(
            model_name=row["model_name"], defaults=row
        )


def reverse_pricing(apps, schema_editor):
    """逆向 noop：不删除价格行。

    回滚 schema（DropTable）本身就会清掉数据，noop 只影响
    "--fake 回滚再前进"等场景；若在这里 delete，反向再正向迁移
    会静默吞掉管理员手工调整过的价格。彻底清理请手动删除。
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("EAW", "0014_deepseek_v4_flash_upgrade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="规范模型名，如 deepseek-v4-flash",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "offpeak_cache_hit_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="闲时·输入（缓存命中），元/百万 tokens",
                        max_digits=8,
                    ),
                ),
                (
                    "offpeak_cache_miss_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="闲时·输入（缓存未命中），元/百万 tokens",
                        max_digits=8,
                    ),
                ),
                (
                    "offpeak_output_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="闲时·输出，元/百万 tokens",
                        max_digits=8,
                    ),
                ),
                (
                    "peak_cache_hit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="高峰·输入（缓存命中）；三列全为 0 表示未配置峰时价，按闲时计",
                        max_digits=8,
                    ),
                ),
                (
                    "peak_cache_miss_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="高峰·输入（缓存未命中）；三列全为 0 表示未配置峰时价，按闲时计",
                        max_digits=8,
                    ),
                ),
                (
                    "peak_output_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="高峰·输出；三列全为 0 表示未配置峰时价，按闲时计",
                        max_digits=8,
                    ),
                ),
                (
                    "pricing_updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="价格最后更新时间（官方调价留痕）",
                    ),
                ),
                (
                    "price_source",
                    models.CharField(
                        default="official-pricing:2026-08-17",
                        help_text="价格来源标记，如官方价格页 + 抓取日期",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Pricing",
                "verbose_name_plural": "Model Pricing",
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="DeepSeekUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(help_text="归一化后的规范模型名", max_length=50),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[("peak", "高峰"), ("offpeak", "空闲")],
                        help_text="计费时刻的真实时段（即使价格回退闲价也记 peak）",
                        max_length=10,
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(
                        help_text="输入 tokens（含缓存命中部分）",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cached_tokens",
                    models.IntegerField(
                        default=0,
                        help_text="其中缓存命中的 tokens",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "output_tokens",
                    models.IntegerField(
                        help_text="输出 tokens（SDK completion_tokens）",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "billed_cache_hit_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="本笔实付单价快照（元/百万 tokens）",
                        max_digits=8,
                    ),
                ),
                (
                    "billed_cache_miss_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="本笔实付单价快照（元/百万 tokens）",
                        max_digits=8,
                    ),
                ),
                (
                    "billed_output_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="本笔实付单价快照（元/百万 tokens）",
                        max_digits=8,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="费用（元）；4 位价格 × 整数 tokens ÷ 1e6 恰好 10 位小数精确",
                        max_digits=14,
                    ),
                ),
                (
                    "billed_at",
                    models.DateTimeField(
                        help_text="计费时刻（响应完成时刻，北京时间 aware）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="可空：后台批量翻译等无用户上下文的调用",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deepseek_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DeepSeek Usage Log",
                "verbose_name_plural": "DeepSeek Usage Logs",
                "ordering": ["-billed_at"],
                "indexes": [
                    models.Index(
                        fields=["billed_at"], name="EAW_deepsee_billed__fb6840_idx"
                    ),
                    models.Index(
                        fields=["model", "band"], name="EAW_deepsee_model_c5856a_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_pricing, reverse_pricing),
    ]
