# Generated by Django 5.2.10 on 2026-03-13 00:00

from django.db import migrations, models


def copy_original_data(apps, schema_editor):
    """将旧字段数据复制到新字段"""
    VocabularyEntry = apps.get_model('EAW', 'VocabularyEntry')
    for entry in VocabularyEntry.objects.all():
        entry.word_og = entry.word
        entry.meaning_og = entry.meaning
        entry.example_og = ''  # 初始为空，原PDF中没有例句字段
        entry.phonetic_og = entry.uk_phonetic or ''
        entry.save(update_fields=['word_og', 'meaning_og', 'example_og', 'phonetic_og'])


def convert_marked_to_text(apps, schema_editor):
    """将 is_marked 从布尔值转换为文本"""
    VocabularyEntry = apps.get_model('EAW', 'VocabularyEntry')
    for entry in VocabularyEntry.objects.all():
        # 当前is_marked是布尔值，True转为'*'，False转为空字符串
        entry.is_marked = '*' if entry.is_marked else ''
        entry.save(update_fields=['is_marked'])


class Migration(migrations.Migration):

    dependencies = [
        ("EAW", "0015_add_is_marked_to_vocabulary_entry"),
    ]

    operations = [
        # Step 1: 添加新字段（允许NULL）
        migrations.AddField(
            model_name='vocabularyentry',
            name='word_og',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vocabularyentry',
            name='meaning_og',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vocabularyentry',
            name='example_og',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vocabularyentry',
            name='phonetic_og',
            field=models.CharField(max_length=200, blank=True, default=''),
        ),
        # Step 2: 数据迁移
        migrations.RunPython(copy_original_data, migrations.RunPython.noop),
        # Step 3: 修改 is_marked 字段类型
        migrations.AlterField(
            model_name='vocabularyentry',
            name='is_marked',
            field=models.CharField(max_length=10, blank=True, default='', help_text='星号标记（原始PDF中的标记）'),
        ),
        # Step 4: 转换 is_marked 数据
        migrations.RunPython(convert_marked_to_text, migrations.RunPython.noop),
        # Step 5: 删除旧字段
        migrations.RemoveField(
            model_name='vocabularyentry',
            name='word',
        ),
        migrations.RemoveField(
            model_name='vocabularyentry',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='vocabularyentry',
            name='has_examples',
        ),
        # Step 6: 重命名新字段到最终名称
        migrations.RenameField(
            model_name='vocabularyentry',
            old_name='word_og',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='vocabularyentry',
            old_name='meaning_og',
            new_name='meaning',
        ),
    ]
