# Generated by Django 6.1.1 on 2026-10-01 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAW', '0015_deepseek_peak_offpeak_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hub_user_id', models.CharField(help_text='study-hub 账号中心的 userId（全局稳定，门户改名不断链）', max_length=64, unique=True, verbose_name='门户用户 ID')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_profile', to=settings.AUTH_USER_MODEL, verbose_name='本地账号')),
            ],
            options={
                'verbose_name': '联邦账号绑定',
                'verbose_name_plural': '联邦账号绑定',
            },
        ),
    ]
