# Generated by Django 6.1.1 on 2026-10-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAW', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepseekusagelog',
            name='billing_party',
            field=models.CharField(choices=[('local', '本地积分'), ('study_hub', '门户积分代扣')], default='local', help_text='本次消费承担方：本地积分 / 门户积分代扣（SSO 绑定用户，存量行默认 local）', max_length=20),
        ),
        migrations.AddField(
            model_name='deepseekusagelog',
            name='deduct_status',
            field=models.CharField(choices=[('pending', '待上报/待人工兜底'), ('ok', '门户已扣'), ('failed', '上报被拒（人工兜底）')], default='ok', help_text='门户上报状态：local 行恒 ok；study_hub 行 pending → ok/failed', max_length=10),
        ),
        migrations.AddField(
            model_name='deepseekusagelog',
            name='remote_ledger_id',
            field=models.BigIntegerField(blank=True, help_text='门户侧流水 id 回写（PointsLedgerId，免扣时为 UsageLedgerId）——人工兜底对账锚点', null=True),
        ),
    ]
