# Generated by Django 5.2.10 on 2026-03-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EAW", "0016_vocabularyentry_refactor"),
    ]

    operations = [
        # 重命名 word 为 word_og
        migrations.RenameField(
            model_name='vocabularyentry',
            old_name='word',
            new_name='word_og',
        ),
        # 重命名 meaning 为 meaning_og
        migrations.RenameField(
            model_name='vocabularyentry',
            old_name='meaning',
            new_name='meaning_og',
        ),
    ]
